"$schema" = 'https://starship.rs/config-schema.json'

palette = 'catppuccin_macchiato'
add_newline = false

format = """
$os\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$git_state\
$package\
$cmd_duration\
$line_break\
$character\
"""

[palettes.catppuccin_mocha]
primary = '#CDD6F4'
secondary = '#BAC2DE'
background = '#1E1E2E'
accent = '#89B4FA'
error = '#F38BA8'
success = '#A6E3A1'
warning = '#F9E2AF'
info = '#94E2D5'
muted = '#585B70'

[palettes.catppuccin_macchiato]
primary   = '#CAD3F5'
secondary = '#B8C0E0'
background = '#24273A'
accent    = '#8AADF4'
error     = '#ED8796'
success   = '#A6DA95'
warning   = '#EED49F'
info      = '#8BD5CA'
muted     = '#5B6078'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:success)'
error_symbol = '[❯](bold fg:error)'

[cmd_duration]
min_time = 2000
format = '[ 󱫑 $duration ]($style)'
style = 'fg:info'
show_milliseconds = false
disabled = false

[os]
disabled = false
style = "fg:success"
format = '[$symbol]($style)'

[os.symbols]
NixOS = "󱄅 "

[directory]
style = "fg:primary"
read_only_style = "fg:warning"
repo_root_style = "bold fg:accent"
format = "[ $path ]($style)"
read_only = "  "
home_symbol = "~"
truncation_symbol = " "
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true

[git_branch]
symbol = " "
style = "fg:accent"
format = '[( $symbol $branch )]($style)'
only_attached = true
ignore_branches = []
truncation_length = 25
truncation_symbol = "..."
always_show_remote = false
disabled = false

[git_commit]
style = "fg:secondary"
format = "[(( $tag)( @$hash) )]($style)"
commit_hash_length = 7
only_detached = true
tag_symbol = "󰓼 "
tag_disabled = false
disabled = false

[git_status]
style = "fg:info"
format = '[($ahead_behind )($all_status )]($style)'
stashed = "*${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
up_to_date = ""
diverged = "⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count}"
deleted = "×${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
ignore_submodules = false
disabled = false

[git_metrics]
format = '[(([+$added]($added_style))([-$deleted]($deleted_style)) )](fg:info)'
added_style = "fg:success"
deleted_style = "fg:error"
only_nonzero_diffs = true
disabled = false

[git_state]
style = "fg:error"
format = '[($state( $progress_current/$progress_total) )]($style bold)'
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
disabled = false

[package]
disabled = false
style = "fg:muted"
symbol = " "
format = '[( $symbol( $version) )]($style)'

[sudo]
disabled = false
style = "fg:accent"
symbol = " "
