theme = "catppuccin_macchiato"

[editor]
true-color = true
line-number = "relative"
mouse = true
bufferline = "multiple"
auto-pairs = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
enable = true
display-messages = true
display-progress-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
ignore = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 3000

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[keys.normal]

# Buffer

"C-s" = ":write"
"C-d" = [":write",":buffer-close"]

# Delete commands

"d" = "delete_selection"
"D" = ["extend_to_line_bounds", "delete_selection"]
